server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mask_order?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123.abcD
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/

mybatis:
  mapper-locations: classpath:/generator/*.xml
  type-aliases-package: edu.fzu.zhishe.reservesystem.generator
  configuration:
    map-underscore-to-camel-case: true
